### ISSUE TITLE
Parse error on activation

### ISSUE THREAD

**Issue by meadows19** [RichardCoffee/privacy-my-way#2]
Hello,

Downloaded and copied to plugins directory. When activating from within the wordpress dashboard, I get a whitescreen with this error:

Parse error: syntax error, unexpected 'return' (T_RETURN), expecting function (T_FUNCTION) in /srv/users/serverpilot/apps/xstaging/public/wp-content/plugins/privacy-my-way/classes/Form/Admin.php on line 239

I'm using php7.0 and the latest wp.

**Comment by RichardCoffee** [comment]
Thanks for bringing this to my attention.

It is entirely my own fault.  I was rewriting some of the code and left in a closing brace by accident.  Had already fixed it by the time I saw your message.

Since you got this error, I believe you downloaded the development version.  I would suggest you go with [the latest release](https://github.com/RichardCoffee/privacy-my-way/releases/latest).  If the latest release =is= what you downloaded, please let me know.  I try to keep the releases as bug free as possible.  The release version will have the version number as part of the directory name, while the development version will not.

Again, thinks for letting me know.  As soon as I am sure I have cleaned up my mess, I will create a development branch so this doesn't happen to anybody else.  It is really something I should have done _before_ I posted that comment on the trac ticket. :(

Please let me know if the problem gets fixed for you.

**Comment by meadows19** [comment]
Yes indeed, I downloaded the development version by mistake.

I've now downloaded and installed the release version and it seems to be working fine.

Thanks for this plugin!
